language: scala
scala:
- 2.11
jdk:
- openjdk7
env:
  global:
  - BRIDGE_USER=travis
  - BRIDGE_ENV=dev
  - secure: SsM07kjCSWjGTFDhkCtTuZdM5WrChFXgRmeMMRJr4JlbtJoaaVUXcXDofZ+4NrESiOvW7CiRXK6Oz3I9eL7vn8RCwlN5jf2OlmD4vKIiiINlvuuEe6hEu738RO7nUGN8SFh2k4ryzJ6XldghjBiBvBEqzVhwXteLhF3AVCsRB1s=
  - secure: kByWq5ygVVnXuBcHKhe6BdcGhUugS1Ux4nbrR/MY23KI7FC1vJ3LCx6N5TIVbOhjwCPwnWNfkydPlfO48hco6gpz8mJ6Sz7OdjyAWb1Ofx/XO5mI+8AIW0P1gXN9jbThSLEaTGUZlrDNfkcfkFUaLJHmmWOQ5CWCPzo5sw2cEDg=
  - secure: Z9NMpRqgtAhaNQLBeSh0iJTgKeNpB3uY4xoYGPNNhDH+rhFe+Urh6RZxfrkF1stAuZXKS1GJe2Kln2GAm2F21DMGagiopcZZIDM456kTDni7A78v/CQR5Sa+PHWk5fITOWTAJSee/pzHaEo7+AIWxhP5DxZah/jJdS3FYM26v/s=
  - secure: aSwn+AOcO2iGFEWcDYJebjglcbADKmlNs1W8NtUjGEFOmuT6nIxyQPva7FAlU4GojnazGQvEwVolFh6D7NPgHVENStflGhUcRLRqeiJV1gBgTV+ot00HRZjEJSacljFFBwQbRW4NfUDzOrE/FClkyCCJnRbKWg3dKONe2dVNEZg=
  - secure: VSoOGViuAi98dBrveHw61gHz0zersdtn8raolu/uzpNQEI1csMdVr09SokygjtiSEt5uIVNma1zkuABRAEgfncT3rYqPq0mdeM+hxPEz2igxEMUXYHx3H9Osbo5oOrTZXnRg18kmzyupUQ98L5Y6/8lg67sgJkPBJEx9dwNKhMY=
  - secure: kTMnfr/AKb5Bp9HuNENNKHsMB+sdlxzIOptVFhA6Gg4poTw+6Y93yUHmqxtAh6WCnihG00877+uQw5IKUww0oL4ppbYgQKwyafhMeIkEpKG/Dycc80oklQe/n7mqHsgRpX3zCeKJG3AZmKsDj/l/WN1i01n68JMeOasGFFQYXpg=
  - secure: fFyFcdKI0utZGSTkeoukkVb4GHUuIpK5VA639prJHyrDhi/rxL8jU8A82av+lYBJHrCRN3ZMfgVxui4uLmqaSacPAcIBIeHyOFq9zEir7TDw8nXhsnAVLJt25i6L731hlEuNDfnroaHV5BCgfkECJcXee07UXhEKFk7vH80KeAk=
  - secure: LtnBJBkSMSzXJlmZQLs3BahpAN0rvF4jRyMuzMK6JaBFqPyiQx9TRRre1wfVsa5KfbnWfLUBEh0XgbbEAzNpVVrB90cfFGUZXgPQKHJI12Z+wqfTGg+f9z63oKjFBw3xe6VWAvzlbMNvoImxnSgHwhluZW9ToXoW9l/oKNLz6os=
  - secure: buGUBaPnZuh8kUotK/iA8xJ0TibbCQpvSaxAwA7UxKlZI414cj8iuV01nsY+Kkwsjr6x0YZAGdzo5YbMFlZX/nsUBZQd8S+fSfm9vmeIBBl4KEmfYxguBpM0MrND1oQ3EYKNpFqlghuJPBsqWCOwfNF8yQALsU+JCdEL5RBqRmk=
  - secure: op8cOe2CvFxaj6GCLzqCVgSJzXofpqP90oS+66IUbECPUyUi6JuViaMGNzaM4mXcHPY5s8Ie0aa9nADlLf/ushBdzDD4/udIthUjU3FOj1azpX9c2qS5K5lLdKhLpqKHdnSm20Sll5AtgxDpfbcCin1Dty87G7N+mHyQtWghMtE=
  - secure: Z+qjzEGwJbnmSYpvb6FLa449FaRaMlHt31InRtlqZVpoKmGFY6hUofYdtBcDdwz/Y2X1QRyCOG88s/TpaNQo0lt7tOETwrkwAfQ6E97hnX7W/Gd4PhDAmkMc8w1PGtuvMl2/ZklLoNDUwbBC+U3tG1UcUlSiNheoAbRviQfFL00=
  - secure: tfbxUsq8+FVvICBJGZIKoWRkWYfQMrm5ODbYL2BnVgLnTBvAxX2tBjzuUkkEVG7eVmoKcIBbisbOIM2epi0lQ2cqHxwbYKb5Qr0EYBQOAl5wRNvbAdiuVmHQhoQtrPMw0uTbihJ8hqCdxN/l+n2lXcQkXeFxJN/9sA/Fm2uT9eU=
  - secure: HepX8b2aoAqu0MPuyEpy+PB2IbkTl/OE8h+CmWoaqDXLEPnYN0tQTdKAmqPk+G5VNb/UzNcCc4b4lMioKyJtx80eQo4io6R68lq/uG9FAkE20J6PhzxB9ZBRULi1BurxrE5lRj3RxU4lXn3bJJYyoormCqTSOai6nCtsIJ4MOaU=
  - secure: hG+O3ytuluFaq+Un3Y7uVrCTlVZWrBufVNd2WluKCNJ62zCUEhFgw43SO3g+/eRuhhPAos0n/y1KeOEpisFdFNCBthlHTA1solk2TVE7pVoJkEtv0DTdt9d5Dg3Rit7XA0QzsMvlErdZrCE7NhfjFe7clwnUQfgIEM7jVlsESro=
  - secure: R0bZSTX5dYjPSv9Skb3EtojMYPkl0hyFjLHknCE8+C1i9jrpT9iQFV3Xb0JrM9MEgdlbKtk19mYGfK7SFL8yjJIXYSR2a/Is5Q5+A7n9HCH1jyEoNDuem9EvCzbY5ywCpb7cHQ0TUK1tMdwDZ/OrMJ6No1eajI/hGRSni4kGcOU=
script:
- sbt test
deploy:
  provider: heroku
  api_key:
    secure: HNTHs81zm46M8mwHlG3hA3WyZeaui0NOYVe9RodlEBfRCl0tVgdDL2XEQsqEsBovrg3qTTFmOr5KYJlaEtqEg2kelgAPNXqariEOzCOZRBYFPpiL9eR5fkxoQ16QSR9DFAMmdLCVlN/y/TgLmdB5hqLeJE6FuWIvNd45qKU0m3Y=
  app:
    develop: bridge-develop
    uat: bridge-uat
    prod: bridge-prod
